#!/bin/bash

function _http_get {
	url=$1
	jq_filter=$2

	curl --header "PRIVATE-TOKEN: $GITLAB_PRIVATE_TOKEN" $url 2>/dev/null | jq -r "$jq_filter"
}


GITLAB_API_BASE_URL=$(git remote get-url origin | sed -r 's_^\s*(https?://)\w+@([a-zA-Z0-9\.]+).*$_\1\2/api/v4_')
GITLAB_PRIVATE_TOKEN=$(pass show gitlab-private-token)

commit_hash=$1
repo_name=$(basename $(git rev-parse --show-toplevel))

gitlab_repo_id=$(_http_get \
	"$GITLAB_API_BASE_URL/projects?search=$repo_name" \
	".[] | select(.name == \"$repo_name\") | .id" \
)

mr_urls=$(_http_get \
	"$GITLAB_API_BASE_URL/projects/$gitlab_repo_id/repository/commits/$commit_hash/merge_requests" \
	".[].web_url" \
)

for url in $mr_urls; do
	echo $url
done
